function normalizeText(value) { return String(value || "").toLowerCase().replace(/[^a-z0-9\s'-]/g, " ").replace(/\s+/g, " ").trim(); }
function escapeHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }
function toTitleCase(value) { return String(value || "").split(/\s+/).filter(Boolean).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }
function firstOpenSlot(collection) { const emptyIndex = collection.findIndex((entry) => entry === null); return emptyIndex === -1 ? 0 : emptyIndex; }
function getTargetServantSlotIndex() { return state.activeServantSlot ?? firstOpenSlot(state.selectedServants); }
function canAddServantToSelection(servantId, targetIndex = getTargetServantSlotIndex()) { const currentServant = state.selectedServants[targetIndex], currentIsSameServant = currentServant?.id === servantId, existingCopies = state.selectedServants.filter((entry) => entry?.id === servantId).length, copiesAfterReplacingTarget = existingCopies - (currentIsSameServant ? 1 : 0); return copiesAfterReplacingTarget < 2; }
function humanizeTrait(traitName) { return normalizeText(String(traitName || "").replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[_-]/g, " ").replace(/\b(class|attribute|alignment)\b/gi, "")); }
function classAbbreviation(className) { return String(className || "").split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(); }
function toAsciiNumber(value) { return Number(String(value || "").replace(/[０-９]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0xFEE0))); }
function extractBondPercent(detail) { const info = extractBondPercents(detail); return info.mlbPercent || 0; }
function isBondGainFunction(func) { const type = normalizeText(func?.funcType || ""); return type === "servantfriendshipup" || type === "bondgain"; }
function extractBondPercentFromFunctions(skills) { if (!Array.isArray(skills)) return 0; let maxPercent = 0; for (const skill of skills) { const functions = Array.isArray(skill.functions) ? skill.functions : []; for (const func of functions) { if (!isBondGainFunction(func)) continue; const svals = Array.isArray(func.svals) ? func.svals : []; for (const sval of svals) { const raw = Number(sval?.Value ?? sval?.value ?? sval?.Rate ?? sval?.rate ?? sval?.val ?? 0); if (!raw) continue; const percent = raw > 100 ? raw / 100 : raw; if (percent > maxPercent) maxPercent = percent; } } } return maxPercent; }
function isBondBoostCE(detail) { const original = String(detail || ""), text = normalizeText(original); if (!original.trim()) return false; if (original.includes("絆")) return true; return text.includes("bond points") || text.includes("bond point") || text.includes("bond gained") || text.includes("bond gain") || text.includes("increases bond") || text.includes("friendship"); }
function isServantPersonalBondCE(_detail, rawCE = null) { return Number(rawCE?.bondEquipOwner ?? 0) > 0; }
function extractBondPercents(detail, ceName = "") { const original = String(detail || ""); if (!isBondBoostCE(original)) return { mlbPercent: 0, ownPercent: 0, isSupportConditional: false }; const jpBondMatches = [...original.matchAll(/絆[^0-9０-９]*(\d+|[０-９]+)\s*[%％]/g)], enBondMatches = [...original.matchAll(/(?:bond|friendship)[^0-9]*(\d+)\s*[%％]/gi)], supportMatches = [...original.matchAll(/(?:サポート|support)[^0-9０-９]*(\d+|[０-９]+)\s*[%％]/gi)]; const values = [...jpBondMatches, ...enBondMatches].map((m) => toAsciiNumber(m[1])).filter(Boolean), supportValues = supportMatches.map((m) => toAsciiNumber(m[1])).filter(Boolean); const mlbPercent = supportValues.length ? Math.max(...supportValues) : values.length ? Math.max(...values) : 0, ownPercent = values.length ? Math.min(...values) : mlbPercent, isSupportConditional = supportValues.length > 0 && ownPercent !== mlbPercent; return { mlbPercent, ownPercent, isSupportConditional: isSupportConditional || normalizeText(ceName) === "chaldea teatime" }; }
function isFlatBondPointCE(ceName = "") { return normalizeText(ceName).includes("portrait"); }
function getCEBondPercent(ce, ceSlotIndex = null) { if (!ce) return 0; const isOwned = ceSlotIndex !== null && Boolean(state.selectedCEOwned[ceSlotIndex]); if (isOwned && Number(ce.ownPercent) > 0) return ce.ownPercent; return ce.percent; }
function matchesPartyWideBondRule(description) { return ["all allies", "all party members", "party members", "all party", "frontline allies", "frontline servants", "frontline party", "all frontline", "including sub members"].some((phrase) => description.includes(phrase)); }
function isExceptSelfCE(description) { return /(except yourself|except self|except equipped servant|excluding yourself|excluding the equipped servant)/.test(description); }

const JP_CE_CONDITION_ALIASES = { "秩序": "lawful", "混沌": "chaotic", "中立": "neutral", "善": "good", "悪": "evil", "中庸": "balanced", "狂": "madness", "夏": "summer", "男性": "male", "女性": "female", "性別不明": "unknown", "天": "sky", "地": "earth", "人": "man", "星": "star", "獣": "beast", "セイバー": "saber", "アーチャー": "archer", "ランサー": "lancer", "ライダー": "rider", "キャスター": "caster", "アサシン": "assassin", "バーサーカー": "berserker", "ルーラー": "ruler", "アヴェンジャー": "avenger", "ムーンキャンサー": "mooncancer", "アルターエゴ": "alterego", "フォーリナー": "foreigner", "プリテンダー": "pretender" };
function getJapaneseBondConditionGroups(detail) { const text = String(detail || ""), groups = []; for (const match of text.matchAll(/〔([^〕]+)〕[^。]*?絆/g)) { const alternatives = String(match[1] || "").split(/(?:または|又は| or )/i); for (const alternative of alternatives) { const conditions = Object.entries(JP_CE_CONDITION_ALIASES).filter(([jp]) => alternative.includes(jp)).map(([, value]) => value); if (conditions.length) groups.push([...new Set(conditions)]); } } return groups; }
function servantMatchesCECondition(servant, condition) { const values = new Set([normalizeText(servant.name), servant.normalizedName, normalizeText(servant.className), servant.gender, servant.attribute, ...(Array.isArray(servant.alignment) ? servant.alignment : []), ...(Array.isArray(servant.traits) ? servant.traits : [])].filter(Boolean).map(normalizeText)); return values.has(normalizeText(condition)); }
function isGenericJapaneseBondCE(detail) { const text = String(detail || ""); return text.includes("絆") && !getJapaneseBondConditionGroups(text).length; }
function doesCEAffectServant(ce, servant, ceSlotIndex, servantSlotIndex, ignoreExceptSelf = false) { if (!ce || !servant) return false; const originalDetail = String(ce.detail || ""), jpConditionGroups = getJapaneseBondConditionGroups(originalDetail); if (jpConditionGroups.length) return jpConditionGroups.some((group) => group.every((condition) => servantMatchesCECondition(servant, condition))); if (isGenericJapaneseBondCE(originalDetail)) return true; const description = ce.normalizedDetail || normalizeText(originalDetail), exceptSelf = isExceptSelfCE(description); if (!ignoreExceptSelf && exceptSelf && ceSlotIndex === servantSlotIndex) return false; if (matchesPartyWideBondRule(description)) return true; if (description.includes(servant.normalizedName)) return true; if (description.includes(`${servant.className} class`) || description.includes(`${servant.className}-class`) || description.includes(`${servant.className} allies`) || description.includes(`${servant.className} servants`)) return true; if (servant.gender !== "unknown" && (description.includes(`${servant.gender} allies`) || description.includes(`${servant.gender} servants`) || description.includes(`${servant.gender} party`))) return true; if (servant.attribute !== "unknown" && (description.includes(`${servant.attribute} allies`) || description.includes(`${servant.attribute} servants`) || description.includes(`${servant.attribute} attribute`))) return true; return servant.traits.some((trait) => trait && description.includes(trait)); }
function getServantBondBonus(servantSlotIndex) { const servant = state.selectedServants[servantSlotIndex]; if (!servant) return 0; const partyBond15Bonus = state.selectedServants.reduce((sum, selectedServant, selectedSlotIndex) => { if (!selectedServant || selectedSlotIndex === servantSlotIndex || !state.selectedServantBond15[selectedSlotIndex]) return sum; return sum + 25; }, 0); const ceBonus = state.selectedCEs.reduce((sum, ce, ceSlotIndex) => { if (!ce || !doesCEAffectServant(ce, servant, ceSlotIndex, servantSlotIndex)) return sum; return sum + getCEBondPercent(ce, ceSlotIndex); }, 0); return ceBonus + partyBond15Bonus; }
function extractPrimaryImage(entry, type) { const groups = [entry?.extraAssets?.faces?.ascension, entry?.extraAssets?.faces?.equip, entry?.extraAssets?.equipFace?.equip, entry?.extraAssets?.charaGraph?.equip, entry?.extraAssets?.charaGraph?.ascension, entry?.extraAssets?.image?.story].filter(Boolean); for (const group of groups) { const value = firstImageFromGroup(group); if (value) return value; } return createTextImage(type === "servant" ? "SVT" : "CE", type === "servant" ? "#1d3557" : "#5a189a"); }
function firstImageFromGroup(group) { if (!group) return ""; if (typeof group === "string") return group; for (const value of Object.values(group)) { const image = firstImageFromGroup(value); if (image) return image; } return ""; }
function createClassIcon(className) { const normalized = normalizeText(className || "unknown") || "unknown"; if (classIconCache.has(normalized)) return classIconCache.get(normalized); const canvas = document.createElement("canvas"); canvas.width = CLASS_ICON_SIZE; canvas.height = CLASS_ICON_SIZE; const context = canvas.getContext("2d"), fill = CLASS_COLORS[normalized] || "#495057"; context.fillStyle = fill; context.beginPath(); context.arc(CLASS_ICON_SIZE / 2, CLASS_ICON_SIZE / 2, 28, 0, Math.PI * 2); context.fill(); context.strokeStyle = "rgba(255,255,255,0.85)"; context.lineWidth = 3; context.stroke(); context.fillStyle = normalized === "ruler" ? "#212529" : "#ffffff"; context.font = "bold 18px sans-serif"; context.textAlign = "center"; context.textBaseline = "middle"; context.fillText(classAbbreviation(normalized), CLASS_ICON_SIZE / 2, CLASS_ICON_SIZE / 2 + 1); const dataUrl = canvas.toDataURL("image/png"); classIconCache.set(normalized, dataUrl); return dataUrl; }
function createTextImage(label, color) { const safeLabel = escapeHtml(String(label || "").split(/\s+/).filter(Boolean).slice(0, 2).join(" ").slice(0, 18) || "FGO"); const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128"><rect width="100%" height="100%" rx="18" fill="${color}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="18" font-weight="700">${safeLabel}</text></svg>`; return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`; }
function bindImageFallbacks(root) { root.querySelectorAll("img[data-fallback-src]").forEach((image) => { image.addEventListener("error", () => { if (image.dataset.fallbackSrc && image.src !== image.dataset.fallbackSrc) image.src = image.dataset.fallbackSrc; }, { once: true }); }); }
